spring.datasource.url=jdbc:mysql://myapp-db.ch48myy0koox.ap-south-1.rds.amazonaws.com:3306/myapp
spring.datasource.username=admin
spring.datasource.password=Chinnu03a#

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
